// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCYhhMIjdZt9WApi6DQDY0B_E4gD6nsUo0',
    appId: '1:551925771354:web:3167bcec526cd76954fc63',
    messagingSenderId: '551925771354',
    projectId: 'lilac-task-a5abc',
    authDomain: 'lilac-task-a5abc.firebaseapp.com',
    storageBucket: 'lilac-task-a5abc.appspot.com',
    measurementId: 'G-VZH0DCGEVJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA1sFrV4rIEXCIQuBsjvOsOBvk1cSlKRy8',
    appId: '1:551925771354:android:cd84bb02e6fdf94d54fc63',
    messagingSenderId: '551925771354',
    projectId: 'lilac-task-a5abc',
    storageBucket: 'lilac-task-a5abc.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyASbebD3Gf3uOd0hg6K5pYlm5vrjcEQBTI',
    appId: '1:551925771354:ios:32fc08251b9494a154fc63',
    messagingSenderId: '551925771354',
    projectId: 'lilac-task-a5abc',
    storageBucket: 'lilac-task-a5abc.appspot.com',
    iosBundleId: 'com.example.lilacTask',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyASbebD3Gf3uOd0hg6K5pYlm5vrjcEQBTI',
    appId: '1:551925771354:ios:32fc08251b9494a154fc63',
    messagingSenderId: '551925771354',
    projectId: 'lilac-task-a5abc',
    storageBucket: 'lilac-task-a5abc.appspot.com',
    iosBundleId: 'com.example.lilacTask',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCYhhMIjdZt9WApi6DQDY0B_E4gD6nsUo0',
    appId: '1:551925771354:web:c4de739116b9ba6254fc63',
    messagingSenderId: '551925771354',
    projectId: 'lilac-task-a5abc',
    authDomain: 'lilac-task-a5abc.firebaseapp.com',
    storageBucket: 'lilac-task-a5abc.appspot.com',
    measurementId: 'G-VKJERQPD7G',
  );
}
